name: insta_clone_first
description: "A new Flutter project."

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.7.0


 
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  logger: ^2.5.0
  cached_network_image: ^3.4.1
  eva_icons_flutter: ^3.1.0
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  firebase_core: ^3.12.1
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  shared_preferences: ^2.5.2
  device_info_plus: ^11.3.2
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


 
flutter:

   
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.otf


   
   
   
   

   
   

   
   

   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
   
